// +build !ignore_autogenerated

/*
Copyright 2019 The Seldon Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by main. DO NOT EDIT.

package v1alpha2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Endpoint) DeepCopyInto(out *Endpoint) {
	*out = *in
	if in.ServicePort != nil {
		in, out := &in.ServicePort, &out.ServicePort
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Endpoint.
func (in *Endpoint) DeepCopy() *Endpoint {
	if in == nil {
		return nil
	}
	out := new(Endpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Parameter) DeepCopyInto(out *Parameter) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Parameter.
func (in *Parameter) DeepCopy() *Parameter {
	if in == nil {
		return nil
	}
	out := new(Parameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveUnit) DeepCopyInto(out *PredictiveUnit) {
	*out = *in
	if in.Children != nil {
		in, out := &in.Children, &out.Children
		*out = make([]PredictiveUnit, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Endpoint.DeepCopyInto(&out.Endpoint)
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]Parameter, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveUnit.
func (in *PredictiveUnit) DeepCopy() *PredictiveUnit {
	if in == nil {
		return nil
	}
	out := new(PredictiveUnit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictorSpec) DeepCopyInto(out *PredictorSpec) {
	*out = *in
	in.Graph.DeepCopyInto(&out.Graph)
	if in.ComponentSpecs != nil {
		in, out := &in.ComponentSpecs, &out.ComponentSpecs
		*out = make([]SeldonPodSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.EngineResources.DeepCopyInto(&out.EngineResources)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.SvcOrchSpec.DeepCopyInto(&out.SvcOrchSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictorSpec.
func (in *PredictorSpec) DeepCopy() *PredictorSpec {
	if in == nil {
		return nil
	}
	out := new(PredictorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictorStatus) DeepCopyInto(out *PredictorStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictorStatus.
func (in *PredictorStatus) DeepCopy() *PredictorStatus {
	if in == nil {
		return nil
	}
	out := new(PredictorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeldonDeployment) DeepCopyInto(out *SeldonDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeldonDeployment.
func (in *SeldonDeployment) DeepCopy() *SeldonDeployment {
	if in == nil {
		return nil
	}
	out := new(SeldonDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeldonDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeldonDeploymentList) DeepCopyInto(out *SeldonDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SeldonDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeldonDeploymentList.
func (in *SeldonDeploymentList) DeepCopy() *SeldonDeploymentList {
	if in == nil {
		return nil
	}
	out := new(SeldonDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeldonDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeldonDeploymentSpec) DeepCopyInto(out *SeldonDeploymentSpec) {
	*out = *in
	if in.Predictors != nil {
		in, out := &in.Predictors, &out.Predictors
		*out = make([]PredictorSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeldonDeploymentSpec.
func (in *SeldonDeploymentSpec) DeepCopy() *SeldonDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(SeldonDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeldonDeploymentStatus) DeepCopyInto(out *SeldonDeploymentStatus) {
	*out = *in
	out.PredictorStatus = in.PredictorStatus
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeldonDeploymentStatus.
func (in *SeldonDeploymentStatus) DeepCopy() *SeldonDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(SeldonDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeldonHpaSpec) DeepCopyInto(out *SeldonHpaSpec) {
	*out = *in
	in.Metrics.DeepCopyInto(&out.Metrics)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeldonHpaSpec.
func (in *SeldonHpaSpec) DeepCopy() *SeldonHpaSpec {
	if in == nil {
		return nil
	}
	out := new(SeldonHpaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeldonPodSpec) DeepCopyInto(out *SeldonPodSpec) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
	in.HpaSpec.DeepCopyInto(&out.HpaSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeldonPodSpec.
func (in *SeldonPodSpec) DeepCopy() *SeldonPodSpec {
	if in == nil {
		return nil
	}
	out := new(SeldonPodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SvcOrchSpec) DeepCopyInto(out *SvcOrchSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	in.Env.DeepCopyInto(&out.Env)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SvcOrchSpec.
func (in *SvcOrchSpec) DeepCopy() *SvcOrchSpec {
	if in == nil {
		return nil
	}
	out := new(SvcOrchSpec)
	in.DeepCopyInto(out)
	return out
}
