# Build the manager binary
FROM golang:1.10.3 as builder

# Copy in the go src
WORKDIR /go/src/github.com/seldonio/seldon-operator
COPY pkg/    pkg/
COPY cmd/    cmd/
COPY vendor/ vendor/

# Build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o manager github.com/seldonio/seldon-operator/cmd/manager

# Copy the controller-manager into a thin image
FROM registry.access.redhat.com/ubi8/ubi
LABEL name="Seldon Operator" \
      vendor="Seldon Technologies" \
      version="v0.3.1" \
      release="1" \
      summary="An Operator to deploy, monitor, explain and manage production machine learning models at scale." \
      description="The Seldon operator for management, monitoring and operations of machine learning systems through the Seldon Engine. Once installed, the Seldon Operator provides multiple functions which facilitate the productisation, monitoring and maintenance of machine learning systems at scale."

WORKDIR /
COPY LICENSE /licenses/
COPY --from=builder /go/src/github.com/seldonio/seldon-operator/manager .
ENTRYPOINT ["/manager"]
